### ISSUE TITLE
Python script for getting releases

### ISSUE THREAD

**Issue by gaalcaras** [chriscool/getreleases#2]
Hi Chris, I finally had some time to work on this. Please check out: https://github.com/gaalcaras/getreleases/commit/362208019c700951f4fc36de162d63ed895908be

It's basically one big Python script that writes the whole Releases section to a markdown file. It also uses a date parameter to only return releases since that date.

I did not start a PR because I'm not sure whether you'd prefer to keep this repo shell only. I could also create a separate Python repository and split the script into different files.

Anyway, tell me what you think :)

**Comment by chriscool** [comment]
Hi Gabriel,
Sorry it looks like I am not properly subscribed to notifications for this repo, so I saw your issue only now.
I think we could have your script in the same repo, and yeah I think there is a good chance that over time your script will be easier to maintain and improve on.
So please start a PR.
Thanks a lot!

**Comment by chriscool** [comment]
By the way the release page for GitLab changed to:

https://about.gitlab.com/blog/categories/releases/

(with an "s" at the end of "release").

**Comment by chriscool** [comment]
get_releases.py is really and we should indeed use it as much as possible. Thanks a lot!
