### ISSUE TITLE
Make it easier to adapt to changes on web pages we scrap

### ISSUE THREAD

**Issue by chriscool** [chriscool/getreleases#5]
I am a bit worried about the number of changes that were needed in https://github.com/chriscool/getreleases/pull/3/commits/c4444eef9e9090b0dcd0bf84763e94fc2642f998 to keep up with a GitLab page change.

In https://github.com/chriscool/getreleases/blob/master/get_gitlab_releases.sh only one regexp change should be needed to keep up.

So I wonder if there is a way to make it easier to adapt to changes.

This is a follow up from #3.

@gaalcaras

**Comment by gaalcaras** [comment]
It doesn't seem like a lot of changes to me, but I do get what you're saying here, I've also been thinking about simplifying the script.

The advantage of using BeautifulSoup is that we can make sure that we get the link to a blog post and check the date of the post at the same time. Also the script will fail gracefully if the layout changes at some point. Using a single regex does make it easier to maintain, but it could also get any link matching the regex and I'm not sure we could check the date of the release.

I'll see if I can find a middle ground here.

**Comment by chriscool** [comment]
This is fixed by #8. Thanks!
