### ISSUE TITLE
Find SourceTree releases

### ISSUE THREAD

**Issue by chriscool** [chriscool/getreleases#6]
As @PreciselyAlyss suggested on https://github.com/git/git.github.io/pull/297#issuecomment-398542857 we could scrap the ["Download Free" URL](https://www.sourcetreeapp.com/download-archives).

It is user-agent specific, but I think that is the most realistic way we can do it, and maybe we can fake different user agents to make sure we don't miss anything.

**Comment by gaalcaras** [comment]
Interestingly enough, I get both Mac and Windows releases under Linux. So maybe we only need to fake a Linux user agent and then scrape that once.

**Comment by chriscool** [comment]
This should be fixed by #8. Thanks @gaalcaras!
